### ISSUE TITLE
Merge or link libelektra-crypto-benchmarks

### ISSUE THREAD

**Issue by petermax2** [ElektraInitiative/rawdata#8]
Do you want to link or merge or copy the raw data from my [repository](https://github.com/petermax2/libelektra-crypto-benchmarks)? The data was created during my research for my BSc thesis.

**Comment by markus2330** [comment]
Yes, if you want please push the data into the repo.

**Comment by petermax2** [comment]
Done :smile:

**Comment by markus2330** [comment]
Thank you!
