### ISSUE TITLE
add misconfiguration error data

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/rawdata#9]
http://rawdata.libelektra.org/

**Comment by ghost** [comment]
https://github.com/ElektraInitiative/rawdata/commit/5fa8db95aa5e2dd0f5426e9371470a706b118d6a

**Comment by markus2330** [comment]
Thank you!

Can you also add a README.md to describe the columns and add yourself to the main readme?

**Comment by ghost** [comment]
I added a README. Can you check if everything is clear?

**Comment by markus2330** [comment]
When the thesis is finished you could put a link to your thesis there.
